# Generated by Django 3.2 on 2023-10-03 19:26

import api.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=254, verbose_name='Фамилия')),
                ('telephone', models.CharField(max_length=15, unique=True, validators=[api.validators.validate_telephone], verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('time_zone', models.CharField(max_length=2, verbose_name='Часовой пояс')),
                ('when_add', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления клиента')),
                ('start_sending', models.TimeField()),
                ('end_sending', models.TimeField()),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код оператора')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, unique=True, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст письма')),
                ('start_time', models.DateTimeField(verbose_name='Старт рассылки')),
                ('end_time', models.DateTimeField(verbose_name='Конец рассылки')),
                ('time_zone', models.CharField(blank=True, max_length=2, null=True, verbose_name='Часовой пояс')),
                ('code_mobile_operator_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_filter', to='api.code', verbose_name='Фильтр по коду оператора')),
                ('tag_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_filter', to='api.tag', verbose_name='Фильтр по тегу')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания письма')),
                ('status', models.BooleanField(default=False, verbose_name='Статус отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail', related_query_name='mail_client', to='api.client', verbose_name='Клиент, которому отправилось письмо')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail', related_query_name='mail_mailing', to='api.mailing', verbose_name='Рассылка, в которой отправляется письмо')),
            ],
            options={
                'ordering': ('create_date', 'status'),
            },
        ),
        migrations.AddField(
            model_name='client',
            name='code_mobile_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.code', verbose_name='Код мобильного оператора'),
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag', verbose_name='Тег'),
        ),
    ]
